from algo.a2c import ActorCritic
from algo.DeepQNetwork import DeepQLearning
from algo.ProximalPolicyOptimization import ProximalPolicyOptimization
from algo.VanillaPolicyGradient import VanillaPolicyGradient